server:
  port: 9800

spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
      register-with-eureka: true  #表示是否将自己注册到 Eureka Server，默认为 true。
      fetch-registry: true # 表示是否从 Eureka Server 获取注册信息，默认为 true。
  instance:
    instance-id: zuulGetway
    prefer-ip-address: true

zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    # user为访问代理名，可使用代理名或者微服务名访问
    store:
      serviceId: consumer
      path: /store/**
  # 隐藏微服务名
  #  ignored-services: provider
  # 隐藏所有微服务名
  ignored-services: "*"
