# mysql
spring:
  application:
    name: user-provider
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/could_factory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: root
    # 初始化，最小，最大连接数
    initialSize: 100
    minidle: 100
    maxActive: 300
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.example.UserProvider.bean

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: user-provider2
logging:
  level:
    root: INFO